In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Churn_Modelling.csv')

In [3]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
df.shape

(10000, 14)

In [5]:
df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [6]:
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [7]:
df.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  object 
 2   Gender           10000 non-null  object 
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64  
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB


In [9]:
df.describe()

CreditScore           Age        Tenure        Balance  NumOfProducts  \
count  10000.000000  10000.000000  10000.000000   10000.000000   10000.000000   
mean     650.528800     38.921800      5.012800   76485.889288       1.530200   
std       96.653299     10.487806      2.892174   62397.405202       0.581654   
min      350.000000     18.000000      0.000000       0.000000       1.000000   
25%      584.000000     32.000000      3.000000       0.000000       1.000000   
50%      652.000000     37.000000      5.000000   97198.540000       1.000000   
75%      718.000000     44.000000      7.000000  127644.240000       2.000000   
max      850.000000     92.000000     10.000000  250898.090000       4.000000   

         HasCrCard  IsActiveMember  EstimatedSalary        Exited  
count  10000.00000    10000.000000     10000.000000  10000.000000  
mean       0.70550        0.515100    100090.239881      0.203700  
std        0.45584        0.499797     57510.492818      0.402769  
min        0.00000        0.000000        11.580000      0.000000  
25%        0.00000        0.000000     51002.110000      0.000000  
50%        1.00000        1.000000    100193.915000      0.000000  
75%        1.00000        1.000000    149388.247500      0.000000  
max        1.00000        1.000000    199992.480000      1.000000

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
onehot_enc = OneHotEncoder(sparse_output=False)

In [12]:
df['Geography'] = onehot_enc.fit_transform(pd.DataFrame(df['Geography']))

In [13]:
df['Gender'] = onehot_enc.fit_transform(pd.DataFrame(df['Gender']))

In [14]:
df

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619        1.0     1.0   42       2       0.00              1   
1             608        0.0     1.0   41       1   83807.86              1   
2             502        1.0     1.0   42       8  159660.80              3   
3             699        1.0     1.0   39       1       0.00              2   
4             850        0.0     1.0   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771        1.0     0.0   39       5       0.00              2   
9996          516        1.0     0.0   35      10   57369.61              1   
9997          709        1.0     1.0   36       7       0.00              1   
9998          772        0.0     0.0   42       3   75075.31              2   
9999          792        1.0     1.0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [15]:
X = df.drop('Exited', axis=1)
y = df['Exited'].copy()

In [16]:
X

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619        1.0     1.0   42       2       0.00              1   
1             608        0.0     1.0   41       1   83807.86              1   
2             502        1.0     1.0   42       8  159660.80              3   
3             699        1.0     1.0   39       1       0.00              2   
4             850        0.0     1.0   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771        1.0     0.0   39       5       0.00              2   
9996          516        1.0     0.0   35      10   57369.61              1   
9997          709        1.0     1.0   36       7       0.00              1   
9998          772        0.0     0.0   42       3   75075.31              2   
9999          792        1.0     1.0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [17]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [20]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8000, 10), (2000, 10), (8000,), (2000,))

In [21]:
len(X_train.columns), len(X_test.columns)

(10, 10)

In [22]:
# num_features = X_train.select_dtypes(include=[np.number]).columns
# cat_features = X_train.select_dtypes(exclude=[np.number]).columns

In [23]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier

In [24]:
# num_pipeline = Pipeline([
#     ('impute', SimpleImputer(strategy='median')),
#     ('scale', StandardScaler())
# ])

# cat_pipeline = Pipeline([
#     ('impute', SimpleImputer(strategy='most_frequent')),
#     ('onehot', OneHotEncoder(sparse_output=False, handle_unknown='ignore'))
# ])

# transformer = ColumnTransformer([
#     ('num', num_pipeline, num_features),
#     ('object', cat_pipeline, cat_features)
# ], remainder='passthrough')

# estimator = RandomForestClassifier()
# full_pipeline = Pipeline([
#     ('preprocessing', transformer),
#     ('estimator', estimator)
# ])

In [25]:
#full_pipeline.fit(X_train, y_train)

In [26]:
#full_pipeline.score(X_train, y_train), full_pipeline.score(X_test, y_test)

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
log_reg = LogisticRegression(max_iter=1000, random_state=42)

In [29]:
log_reg.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [30]:
preds = log_reg.predict(X_test)
preds

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [31]:
log_reg.score(X_train, y_train), log_reg.score(X_test, y_test)

(0.78725, 0.8005)

In [32]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report, confusion_matrix

In [33]:
accuracy_score(y_test, preds)

0.8005

In [34]:
recall_score(y_test, preds, average='weighted')

0.8005

In [35]:
precision_score(y_test, preds, average='weighted')

0.7409119561237059

In [36]:
f1_score(y_test, preds, average='weighted')

0.737248367147662

In [37]:
classification_report(y_test, preds)

'              precision    recall  f1-score   support\n\n           0       0.81      0.98      0.89      1607\n           1       0.45      0.07      0.12       393\n\n    accuracy                           0.80      2000\n   macro avg       0.63      0.53      0.51      2000\nweighted avg       0.74      0.80      0.74      2000\n'

In [38]:
confusion_matrix(y_test, preds)

array([[1573,   34],
       [ 365,   28]], dtype=int64)

In [39]:
from imblearn.over_sampling import SMOTE

In [40]:
smote = SMOTE(random_state=42)

In [41]:
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

In [42]:
y_resampled.value_counts()

Exited
0    6356
1    6356
Name: count, dtype: int64

In [43]:
log_reg = LogisticRegression(max_iter=1000, random_state=42)

In [45]:
log_reg.fit(X_resampled, y_resampled)

LogisticRegression(max_iter=1000, random_state=42)

In [46]:
preds_balanced = log_reg.predict(X_test)

In [47]:
preds_balanced

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [48]:
accuracy_score(y_test, preds_balanced)

0.632

In [49]:
classification_report(y_test, preds_balanced)

'              precision    recall  f1-score   support\n\n           0       0.89      0.62      0.73      1607\n           1       0.30      0.68      0.42       393\n\n    accuracy                           0.63      2000\n   macro avg       0.60      0.65      0.58      2000\nweighted avg       0.77      0.63      0.67      2000\n'

In [50]:
confusion_matrix(y_test, preds_balanced)

array([[997, 610],
       [126, 267]], dtype=int64)

In [51]:
from sklearn.ensemble import RandomForestClassifier

In [52]:
rfc = RandomForestClassifier(random_state=42)

In [53]:
rfc.fit(X_resampled, y_resampled)

RandomForestClassifier(random_state=42)

In [54]:
rfc_preds = rfc.predict(X_test)

In [55]:
rfc_preds

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [56]:
accuracy_score(y_test, rfc_preds)

0.832

In [61]:
print(classification_report(y_test, rfc_preds))

              precision    recall  f1-score   support

           0       0.89      0.90      0.90      1607
           1       0.58      0.54      0.56       393

    accuracy                           0.83      2000
   macro avg       0.73      0.72      0.73      2000
weighted avg       0.83      0.83      0.83      2000



In [62]:
print(confusion_matrix(y_test, rfc_preds))

[[1450  157]
 [ 179  214]]
